name: CICD

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: choose an environment to run the cicd pipeline
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
          

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "git clone<repo-url>"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build docker container
        run: echo "docker container build"
  test:
    needs: [code,build]
    runs-on: ubuntu-latest
    steps:
      - name: test the container
        run: echo "testing the container"
  deploy:
    if: inputs.environment == 'dev'
    needs: [code,build,test]
    runs-on: ubuntu-latest
    steps:
      - name: deploying the app
        run: echo "docker compose deployed the app"
  
